### ISSUE TITLE
Careful with strlen

### ISSUE THREAD

**Issue by ordago** [kaiopiola/keygen-package#7]
https://github.com/kaiopiola/keygen-package/blob/a39b6852756fce60af3dbf96c73f9281f1d2043b/src/Key.php#L81

`strlen('CCC')`
3

`strlen('ÇÇÇ')`
6

**Comment by kaiopiola** [comment]
Could ```mb_strlen($str, "UTF-8")``` be the right solution for this?

Reference:
https://pt.stackoverflow.com/questions/273724/d%C3%BAvida-fun%C3%A7%C3%A3o-php-mb-strlen#:~:text=Concluindo%2C%20a%20fun%C3%A7%C3%A3o%20strlen(),e%20recomendado%20pela%20W3.org.

**Comment by ordago** [comment]
I think that would work.
