### ISSUE TITLE
Setters don't need to return a value

### ISSUE THREAD

**Issue by ordago** [kaiopiola/keygen-package#9]
https://github.com/kaiopiola/keygen-package/blob/501660d6388d2cdc7df86fdbc73129483b8c20c7/src/Key.php#L37-L42

The value returned is the same as the parameter passed.

Also, the phpdoc says it returns a string, but the return type will be the type of the parameter passed. Which is not assured it will be a string.

**Comment by kaiopiola** [comment]
`$this->letters = $s;`

Is this sufficient?

**Comment by ordago** [comment]
For setting the value, yes.
